apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    component: plantd-metrics-endpoint
  name: cadvisor-service-monitor
  namespace: kube-system
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    honorLabels: true
    interval: 30s
    port: https-metrics
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    port: https-metrics 
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
    honorLabels: true
    interval: 30s
    path: /metrics/cadvisor
  jobLabel: kubelet 
  namespaceSelector:
    matchNames: 
    - kube-system
  selector:
    matchLabels:
      k8s-app: kubelet
